POST http://localhost:50123/api/camel-milo
Content-Type: application/json
Accept: application/json

{
  "produceUri":"milo-client:opc.tcp://VAL031.gv.local:53530/OPCUA/SimulationServer?allowedSecurityPolicies=None&samplingInterval=500",
  "payload":[
    {
      "nodeId":{
        "namespaceIndex":3,
        "identifier":1002
      },
      "value":"ZPH-V123-00001"
    },
    {
      "nodeId":{
        "namespaceIndex":3,
        "identifier":1003
      },
      "value":"PC-017P"
    },
    {
      "nodeId":{
        "namespaceIndex":3,
        "identifier":1004
      },
      "value":1
    },
    {
      "nodeId":{
        "namespaceIndex":3,
        "identifier":1005
      },
      "value":"MFG-V123-000001"
    },
    {
      "nodeId":{
        "namespaceIndex":3,
        "identifier":1006
      },
      "value":50
    },
    {
      "nodeId":{
        "namespaceIndex":3,
        "identifier":1007
      },
      "value":0
    },
    {
      "nodeId":{
        "namespaceIndex":3,
        "identifier":1008
      },
      "value":"Porta A5 Favo Ppl 28 + Mdf 3 OF 2000x800x35"
    }
  ]
}

###

    # Val | ACL010 AG92 Sorter CPU 1515TF2PN
    # Username: Valco
    # Password: ValcoAG92Sorter
# opc.tcp://172.16.32.159:4840
#   "produceUri":"milo-client:opc.tcp://172.16.32.159:4840?allowedSecurityPolicies=None&username=Valco&password=ValcoAG92Sorter",
# "produceUri":"milo-client:opc.tcp://Valco:ValcoAG92Sorter@172.16.32.159:4840?allowedSecurityPolicies=None",
# "produceUri":"milo-client:opc.tcp://172.16.32.159:4840?allowedSecurityPolicies=None",

POST http://localhost:50123/api/camel-milo
Content-Type: application/json
Accept: application/json

{

  "produceUri":"milo-client:opc.tcp://172.16.32.159:4840?allowedSecurityPolicies=None",
  "payload":[
    {
      "nodeId":{
        "namespaceIndex": 4,
        "identifier": 3
      },
      "value": 15,
      "dataType": "UShort"
    }
  ]
}
