###
POST http://localhost:50123/api/nodes
Content-Type: application/json
Accept: application/json

{
  "namespaceIndex": 3,
  "identifier": 1002,
  "value": "Test 7",
  "type": "java.lang.String"
}

###
POST http://localhost:50123/api/nodes
Content-Type: application/json
Accept: application/json

{
  "namespaceIndex": 3,
  "identifier": 9999999,
  "value": "Faill",
  "type": "java.lang.String"
}
