server.port: 50123

spring:
  application:
    name: Nexiles OPC UA Client Example

logging:
  level:
    com.nexiles: DEBUG
    org.eclipse.milo: INFO
    org.apache.camel: DEBUG

nexiles:
  # endpoint: milo-client:tcp://192.168.123.2:4840?allowedSecurityPolicies=None&node=RAW(ns=3;s="103_Servo_G"."M150_Data"."POS_ACT")
  # endpoint: milo-client:tcp://127.0.0.1:12686/example?allowedSecurityPolicies=None&samplingInterval=500&node=RAW(ns=2;s=HelloWorld/ScalarTypes/Double)
#  endpoint: milo-client:tcp://127.0.0.1:12686/example?allowedSecurityPolicies=None&samplingInterval=500&node=RAW(ns=2;s=HelloWorld/Dynamic/Double)


#  endpoint: milo-client:opc.tcp://VAL031.gv.local:53530/OPCUA/SimulationServer?allowedSecurityPolicies=None&samplingInterval=500&node=RAW(ns=2;i=1002)
 endpoint: milo-client:opc.tcp://VAL031.gv.local:53530/OPCUA/SimulationServer?allowedSecurityPolicies=None&samplingInterval=500&node=RAW(ns=3;i=1002)
  #endpoint: milo-client:opc.tcp://VAL031.gv.local:53530/OPCUA/SimulationServer?allowedSecurityPolicies=None&samplingInterval=500?node=RAW(ns=2;s=Methods)=RAW(ns=2;s=Methods/sqrt(x))=true=true


camel:
  component:
    milo-client:
      default-configuration:
        allowed-security-policies: None
        override-host: true
