server.port: 50123

spring:
  application:
    name: Grupo Valco OPC UA Client Example

logging:
  level:
    com.camelopcua.component:
      device0006: ERROR
      prosyssimulationserver: DEBUG
    org.eclipse.milo: INFO
    org.apache.camel: INFO

camel:
  component:
    milo-client:
      default-configuration:
        allowed-security-policies: None
        override-host: true


com.gv.component:
  milo-client:

    # -------------------------------------------------------------#
    # SIMATIC.S7-1500.OPC-UA.Application:AG63-PLC
    # opc.tcp://172.16.35.105:4840  #
    #
    # Emp | PLC Simens 001 Agix (RFID Automaton)
    # -------------------------------------------------------------#
    device-0002:
      consumer:
        route-id: PC-017P Emp | PLC Simens 001 Agix (RFID Automaton) Consumer
        input: milo-client:opc.tcp://172.16.35.105:4840?allowedSecurityPolicies=None&samplingInterval=500&node=RAW(ns=4;i=3)
        output: direct:start-device-0006
      aggregator:
        route-id: PC-017P Emp | Hot Press Outlet PLC Aggregator
        input: direct:start-device-0006
        enricher: milo-client:opc.tcp://172.16.35.100:4840?allowedSecurityPolicies=None&samplingInterval=500
        enricher-header-node-ids: ns=4;i=3, ns=4;i=4
        output: mock:test


    # -------------------------------------------------------------#
    # SIMATIC.S7-1500.OPC-UA.Application:AG95-PLC
    # opc.tcp://172.16.35.100:4840
    #
    # Emp | PC-017 Hot Press Outlet PLC
    # -------------------------------------------------------------#
    device-0006:
      consumer:
        route-id: PC-017P Emp | Hot Press Outlet PLC Consumer
        input: milo-client:opc.tcp://172.16.35.100:4840?allowedSecurityPolicies=None&samplingInterval=500&node=RAW(ns=4;i=2)
        output: direct:start-device-0006
      aggregator:
        route-id: PC-017P Emp | Hot Press Outlet PLC Aggregator
        input: direct:start-device-0006
        enricher: milo-client:opc.tcp://172.16.35.100:4840?allowedSecurityPolicies=None&samplingInterval=500
        enricher-header-node-ids: ns=4;i=3, ns=4;i=4, ns=4;i=5, ns=4;i=6
#        output: mock:test
        output: http://172.16.2.73:50001/api/do-post?httpMethod=POST

    prosys-simulation-server:
      consumer:
        route-id: Prosys OPC Simulation Server Consumer
        input: milo-client:opc.tcp://VAL031.gv.local:53530/OPCUA/SimulationServer?allowedSecurityPolicies=None&samplingInterval=500&node=RAW(ns=3;i=1005)
        output: direct:start-prosys-simulation-server
      aggregator:
        route-id: Prosys OPC Simulation Server Consumer Aggregator
        input: direct:start-prosys-simulation-server
        enricher: milo-client:opc.tcp://VAL031.gv.local:53530/OPCUA/SimulationServer?allowedSecurityPolicies=None&samplingInterval=500
        enricher-header-node-ids: ns=3;i=1002, ns=3;i=1005
        output: http://172.16.2.73:50001/api/do-post?httpMethod=POST


    # -------------------------------------------------------------#
    # ????????????????????
    # opc.tcp://172.16.32.159:4840
    #
    # Val | ACL010 AG92 Sorter CPU 1515TF2PN
    # Username: Valco
    # Password: ValcoAG92Sorter
    # -------------------------------------------------------------#
    acl-010-sorter:
      consumer:
        route-id: ACL010 Sorter AG92
        input: milo-client:opc.tcp://172.16.32.159:4840?allowedSecurityPolicies=None&samplingInterval=500&node=RAW(ns=4;i=3)
        output: direct:start-acl-010-sorter
      aggregator:
        route-id: ACL010 Sorter AG92 Consumer Aggregator
        input: direct:start-acl-010-sorter
        enricher: milo-client:opc.tcp://172.16.32.159:4840?allowedSecurityPolicies=None&samplingInterval=500
        enricher-header-node-ids: ns=4;i=2, ns=4;i=15, ns=4;i=16
        output: mock:test
